      - name: Deploy (sam deploy, ignore "No changes to deploy")
        run: |
          # Run sam deploy, capture output and exit code
          sam deploy --stack-name TodoStack \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-confirm-changeset \
            --region ${{ env.AWS_REGION }} \
            --resolve-s3 2>&1 | tee deploy.log
          rc=${PIPESTATUS[0]}

          # If sam exited with non-zero, check whether it's "No changes to deploy"
          if [ "$rc" -ne 0 ]; then
            if grep -q "No changes to deploy" deploy.log; then
              echo "No changes to deploy — treating as success."
            else
              echo "sam deploy failed. See deploy.log below:"
              tail -n +1 deploy.log
              exit $rc
            fi
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
